# environment.yml
name: tmseegpy-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  # Core scientific packages
  - numpy>=1.16.0
  - scipy>=1.2.0
  - scikit-learn
  # MNE and related
  - mne>=1.1
  - mne-base
  # Deep learning
  - pytorch
  - tensorly
  # Visualization
  - matplotlib
  - seaborn
  # Utilities
  - tqdm
  - psutil
  - pooch
  - construct
  - pip
  - pip:
    - mne-faster


