name: GUI Release
on:
  push:
    tags:
      - 'gui-v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          cd tmseegpy-gui-react
          npm ci
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          ESLINT_NO_DEV_ERRORS: true
          CI: false
        with:
          github_token: ${{ secrets.GH_RELEASE_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/gui-v') }}
          package_root: tmseegpy-gui-react